export const AUTHENTICATE_REQUEST = 'auth/AUTHENTICATE_REQUEST';
export const AUTHENTICATE_SUCCESS = 'auth/AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILURE = 'auth/AUTHENTICATE_FAILURE';

export const LOGOUT_REQUEST = 'auth/LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'auth/LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'auth/LOGOUT_FAILURE ';

export const FORGOT_PASSWORD_REQUEST = 'auth/FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'auth/FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'auth/FORGOT_PASSWORD_FAILURE';
