export const ADD_CAT_REQUEST = 'ADD_CAT_REQUEST';
export const ADD_CAT_SUCCESS = 'ADD_CAT_SUCCESS';
export const ADD_CAT_ERROR = 'ADD_CAT_ERROR';

export const DELETE_CAT_REQUEST = 'DELETE_CAT_REQUEST';
export const DELETE_CAT_SUCCESS = 'DELETE_CAT_SUCCESS';
export const DELETE_CAT_ERROR = 'DELETE_CAT_ERROR';

export const EDIT_CAT_REQUEST = 'EDIT_CAT_REQUEST';
export const EDIT_CAT_SUCCESS = 'EDIT_CAT_SUCCESS';
export const EDIT_CAT_ERROR = 'EDIT_CAT_ERROR';
