export const ADD_PERSON_REQUEST = 'ADD_PERSON_REQUEST';
export const ADD_PEROSN_SUCCESS = 'ADD_PEROSN_SUCCESS';
export const ADD_PERSON_ERROR = 'ADD_PERSON_ERROR';

export const DELETE_PERSON_REQUEST = 'DELETE_PERSON_REQUEST';
export const DELETE_PERSON_SUCCESS = 'DELETE_PERSON_SUCCESS';
export const DELETE_PERSON_ERROR = 'DELETE_PERSON_ERROR';

export const EDIT_PERSON_REQUEST = 'EDIT_PERSON_REQUEST';
export const EDIT_PERSON_SUCCESS = 'EDIT_PERSON_SUCCESS';
export const EDIT_PERSON_ERROR = 'EDIT_PERSON_ERROR';
